package analyzer

import "testing"

func TestIsGeneratedFile(t *testing.T) {
	tests := []struct {
		name string
		file string
		body string
		want bool
	}{
		{"protobuf suffix", "service.pb.go", "package x", true},
		{"generated suffix", "thing_generated.go", "package x", true},
		{"mock prefix", "mock_client.go", "package x", true},
		{"zz generated prefix", "zz_generated.deepcopy.go", "package x", true},
		{"code generated marker", "client.go", "// Code generated by tool. DO NOT EDIT.\npackage x", true},
		{"marker string literal", "client.go", "package x\nconst marker = \"DO NOT EDIT\"", false},
		{"ordinary source", "client.go", "package x\nfunc Run() {}", false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := IsGeneratedFile(tt.file, []byte(tt.body))
			if got != tt.want {
				t.Fatalf("IsGeneratedFile(%q) = %v, want %v", tt.file, got, tt.want)
			}
		})
	}
}
